### ISSUE TITLE
Auto trailer doesn’t play with OpenMeta widget

### ISSUE THREAD

**Issue by kbxy88** [cartmandos/skin.titan.bingie#12]
I have widgets setup to point to openmeta-blockbusters(tmbd) or openinfo - top rated i notice the trailers don’t auto play in spotlight like my other widgets do such as the one that points to a Seren

Not sure where the issue lies

18.1

**Comment by cartmandos** [comment]
I'm not familiar with these addons but...
Is it scanned to library (integrated with a database ID) or not?
would help to get as much details as you can and paste a debug log (or look specifically for 'youtube') if it sends a query for that title or not...

**Comment by kbxy88** [comment]
debug log:http://paste.kodi.tv/oqimagaziw

I see YouTube query’s for my other addon, but not for this widget. No, not scanned to library

**Comment by cartmandos** [comment]
Since I don't have this addon let's try something.
Edit includesAnimation.xml, find 'set_alarm_trailer_", there will couple of for each interval time. say you use 5 seconds, then under 'set_alarm_trailer_5' look for:
"playtraileryoutube,title=$INFO[ListItem.Title]" and change ListItem.Title -> ListItem.Label

Report back ;)

**Comment by kbxy88** [comment]
Hey sorry for the delay. I tried changing that each time it appeared in that file, and no change.

**Comment by cartmandos** [comment]
alright, first off - just making sure. In settings you have 'enable youtube lookup' on right? otherwise, it will not allow youtube search in the first place (for tvshows and addons).
next, it seems from your feedback that youtube is not getting a query search.
We established that it is not an item from the library.
then one thing left to try if all above is correct -
inside set_trailer that you edited before:
try to delete:
'[String.IsEqual(ListItem.DBType,movie) | String.IsEqual(ListItem.DBType,tvshow) | String.IsEqual(ListItem.DBType,episode)]'
ONLY for non-library items (there will be a comment in code).
Then check to see if trailer is running or at least in log if youtube is searching for SOME search term.
